---
### EXAMPLE ###
#- name: app1
#  hostname: 'app1'
#  private_ip: '192.168.10.4'
#  box: 'ubuntu/xenial64'
#  guest: ['9000', '8000', '7000']
#  host: ['9000', '9100', '9101']
#  provis: ['ansible', 'shell']
#  playbook: ['app1.yml','test.sh']
#  provider: 'virtualbox'
#  ram: '2048'
#- name: app2
#  hostname: 'app2'
#  private_ip: '192.168.10.6'
#  box: 'ubuntu/xenial64'
#  guest: ['9001']
#  host: ['9001']
#  provis: ['shell', 'puppet']
#  playbook: ['example.sh','pup.pp']
#  provider: 'virtualbox'
#  ram: '512'
